In [2]:
import numpy as np

In [2]:
a = np.random.randn(5,1)

In [15]:
a

array([[ 0.97054278],
       [-0.03173173],
       [-0.49218827],
       [-1.2924468 ],
       [ 0.01163649]])

In [16]:
a.shape

(5, 1)

In [20]:
assert(a.shape==(5,2)), "Shape error %r" % a

AssertionError: Shape error array([[ 0.97054278],
       [-0.03173173],
       [-0.49218827],
       [-1.2924468 ],
       [ 0.01163649]])

In [17]:
assert(a.shape==(5,1)), "Shape error"

In [21]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [22]:
d=np.dot(a, b)

In [23]:
d

array([[-0.64184191, -0.98845107],
       [ 1.68546813,  0.55624946],
       [-0.95856719, -0.37857393],
       [-2.77962932, -1.58081153]])

In [24]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [25]:
c.shape

(2, 3)

In [26]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [27]:
c

array([[-1.80634592,  0.23807237, -0.80457247],
       [-0.81872643, -0.23711729,  1.39602657],
       [ 1.59513232,  0.41108859,  0.07044587]])

In [3]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [5]:
B.shape

(4, 1)